//Tablas

Table CUIDADOR {
    cuidador_id int [pk, increment]
    nombre varchar
    email varchar [unique]
    telefono varchar
    fecha_registro datetime
}

Table PERSONA_MAYOR {
    persona_mayor_id int [pk, increment]
    nombre varchar
    fecha_nacimiento date
    nivel_dependencia varchar
    direccion varchar
}

Table ASIGNACION_CUIDADO {
    asignacion_id int [pk, increment]
    cuidador_id int [ref: > CUIDADOR.cuidador_id, note: 'gestiona']
    persona_mayor_id int [ref: > PERSONA_MAYOR.persona_mayor_id]
    relacion_parentesco varchar
    fecha_inicio date
}

Table MEDICAMENTO {
    medicamento_id int [pk, increment]
    nombre varchar
    unidad_medida varchar
}

Table TRATAMIENTO {
    tratamiento_id int [pk, increment]
    persona_mayor_id int [ref: > PERSONA_MAYOR.persona_mayor_id]
    medicamento_id int [ref: > MEDICAMENTO.medicamento_id]
    dosis varchar
    hora_programada time
    fecha_inicio date
    fecha_fin date
}

Table REGISTRO_MEDICAMENTO {
    registro_id int [pk, increment]
    tratamiento_id int [ref: > TRATAMIENTO.tratamiento_id]
    cuidador_id int [ref: > CUIDADOR.cuidador_id]
    fecha_hora datetime
    dentro_ventana boolean
    observacion varchar
}

Table ACTIVIDAD_CUIDADO {
    actividad_id int [pk, increment]
    persona_mayor_id int [ref: > PERSONA_MAYOR.persona_mayor_id]
    cuidador_id int [ref: > CUIDADOR.cuidador_id]
    tipo_actividad varchar
    fecha_hora datetime
    detalle varchar
    observacion varchar
}

Table CITA_MEDICA {
    cita_id int [pk, increment]
    persona_mayor_id int [ref: > PERSONA_MAYOR.persona_mayor_id]
    especialidad varchar
    fecha_hora datetime
    lugar varchar
    estado varchar
    notas varchar
}

Table EVALUACION_SOBRECARGA {
    evaluacion_id int [pk, increment]
    cuidador_id int [ref: > CUIDADOR.cuidador_id]
    fecha date
    puntaje_zarit int
    nivel_sobrecarga varchar
}

Table ALERTA {
    alerta_id int [pk, increment]
    persona_mayor_id int [ref: > PERSONA_MAYOR.persona_mayor_id]
    cuidador_id int [ref: > CUIDADOR.cuidador_id]
    tipo_alerta varchar
    fecha_generada datetime
    estado varchar
    descripcion varchar
}

// Etiquetas relaciones

Ref gestiona: ASIGNACION_CUIDADO.cuidador_id > CUIDADOR.cuidador_id